eclipse/triquetrum

org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ConnectionCreateFeature.java
org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ModelElementCreateFeature.java
org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/util/EditorUtils.java

We can use ptolemy's CompositeEntity.uniqueName() in
ConnectionCreateFeature and ModelElementCreateFeature.

#14 : ensure unique names are used for creating new elements

---

org.eclipse.triquetrum.workflow.ui/src/main/java/org/eclipse/triquetrum/workflow/ui/AbstractPlaceableSWT.java
org.eclipse.triquetrum.workflow.ui/src/main/java/org/eclipse/triquetrum/workflow/ui/SizeAttribute.java
org.eclipse.triquetrum.workflow.ui/src/main/java/org/eclipse/triquetrum/workflow/ui/WindowPropertiesAttribute.java

Bug 22: @see tags cause errors in Eclipse build

Summary: Removed @see tags to fix Eclipse triq.target build

---

org.eclipse.triquetrum.workflow.ui/src/main/java/org/eclipse/triquetrum/workflow/ui/AbstractPlaceableSWT.java
org.eclipse.triquetrum.workflow.ui/src/main/java/org/eclipse/triquetrum/workflow/ui/SizeAttribute.java
org.eclipse.triquetrum.workflow.ui/src/main/java/org/eclipse/triquetrum/workflow/ui/WindowPropertiesAttribute.java

Bug #22: @see tags cause errors in Eclipse build

Summary: Reentered deleted of @see tags that I accidentally overwrote.

---

javadoc/.gitignore
javadoc/pom.xml

Bug #31 A support for JavaDoc to pom.xml 
This required adding javadoc/pom.xml.
Unfortunately, we need to list each bundle by hand in that file.
Details are at
https://chess.eecs.berkeley.edu/triq/wiki/Main/Hudson#JavaDoc

Summary: Added the javadoc plugin.

---

pom.xml

Bug #31 A support for JavaDoc to pom.xml

Summary: Updating pom.xml to include javadoc module

---

org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/views/NamedObjDialog.java

The fix involves forcing the focus on the dialog view component, right before closing it.
Thanks to Davy De Durpel, for reproducing the reported issue, implementing the fix and testing it.
Christopher, can you try this out to see if it works for you as well?

#7 : fix MAC OSX focus-lost issue on text fields in EMF forms

---

README.md

Apparently, Links to wiki pages cannot have trailing slashes.

---

org.eclipse.triquetrum.workflow.editor.palette/plugin.xml

and throws an exception in the head
Oddly, moving the definition of TrigFunction ealier in the file fixed
this? 

Fixed bug #86: Dragging a TrigFunction actor fails in the May 29 build

---

org.eclipse.triquetrum.common/triquetrumCleanUpSettings.xml
org.eclipse.triquetrum.common/triquetrumFormatterSettings.xml

Bug #79: Clean the code
See https://wiki.eclipse.org/Triquetrum/Coding_Style

Added Eclipse Formatter and Clean Up settings files.

---

org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target

Added https://eclipseguru.github.io/missing-swt-fragments/
as a p2 repo to avoid mvn compile error:
"Unable to satisfy dependency from org.eclipse.swt
3.105.0.v20160603-0902 to org.eclipse.swt.gtk.linux.aarch64
[3.105.0.v20160603-0902]."
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=491951#c35

Fixed multi-platform build after last change for Bug #66

---

org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target

Reverts eclipse/triquetrum#101
Backing out failed port to Neon.

Revert "Fixed multi-platform build after last change for Bug #66"

---

org.eclipse.triquetrum.repository/Triquetrum.product
org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target

Reverts eclipse/triquetrum#100
Update to Neon is causing problems with Tycho and mvn compile.

Revert "Update to Neon. Bug #66 (Mac OS X Edit Menu) still not fixed"

---

org.eclipse.triquetrum.repository/Triquetrum.product
org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd

Note that we need to use swt fragments because of Bug #491951:  Unable
to satisfy dependency from org.eclipse.swt v20160317 to
org.eclipse.swt.gtk.linux.aarch64, see
https://bugs.eclipse.org/bugs/show_bug.cgi?id=491951#c35

Triquetrum now builds on Neon, fixing Bug #104

---

org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd

Use the new ptII repo at
https://chess.eecs.berkeley.edu/triq/p2/osgi-2-0/
See
https://wiki.eclipse.org/Triquetrum/Ptolemy/osgi-2-0#The_Ptolemy_II_osgi-2-0_p2_repository
This will allow Bug #114 Create a p2 site for the Ptolemy II bundles  
to be closed

Use the new ptII p2 repo.  Bug #114

---

pom.xml

The Hudson Triquetrum build cannot access 
https://chess.eecs.berkeley.edu/triq/p2/osgi-2-0/
It could be a proxy problem during the "mvn clean install" process

Added target to print env to help solve proxy problem. Bug #492412

---

examples/org.eclipse.triquetrum.python.service.example/META-INF/MANIFEST.MF
examples/org.eclipse.triquetrum.workflow.actor.plot.palette/META-INF/MANIFEST.MF
examples/org.eclipse.triquetrum.workflow.actor.plot/META-INF/MANIFEST.MF
org.eclipse.triquetrum.common/META-INF/MANIFEST.MF
org.eclipse.triquetrum.dependencies/META-INF/MANIFEST.MF
org.eclipse.triquetrum.logging.dvp/META-INF/MANIFEST.MF
org.eclipse.triquetrum.processing.actor/META-INF/MANIFEST.MF
org.eclipse.triquetrum.processing.api/META-INF/MANIFEST.MF
org.eclipse.triquetrum.processing.model.impl/META-INF/MANIFEST.MF
org.eclipse.triquetrum.processing.service.impl.example/META-INF/MANIFEST.MF
org.eclipse.triquetrum.processing.service.impl/META-INF/MANIFEST.MF
org.eclipse.triquetrum.processing.test/META-INF/MANIFEST.MF
org.eclipse.triquetrum.python.actor/META-INF/MANIFEST.MF
org.eclipse.triquetrum.python.service/META-INF/MANIFEST.MF
org.eclipse.triquetrum.repository/Triquetrum.product
org.eclipse.triquetrum.scisoft.analysis.rpc.test/META-INF/MANIFEST.MF
org.eclipse.triquetrum.scisoft.analysis.rpc/META-INF/MANIFEST.MF
org.eclipse.triquetrum.validation.api/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.actor.ui/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.api/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.editor.palette/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.editor/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.execution.impl/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.model.edit/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.model.editor/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.model.viewmodel/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.model/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.repository.impl.filesystem/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.repository.test/META-INF/MANIFEST.MF
org.eclipse.triquetrum.workflow.ui/META-INF/MANIFEST.MF

https://www.eclipse.org/projects/handbook/#release-faq
Version numbers of incubation products should be less than 1.0.
Used the following command:
sed -i ''  's/\(^Bundle-Version:.*$\)/Bundle-Version: 0.1.0.qualifier/'
examples/*/META-INF/MANIFEST.MF *triq*/META-INF/MANIFEST.MF

Update version from 1.0 to 0.1.0 for incubation. Bug #129

---

org.eclipse.triquetrum.core.feature/build.properties
org.eclipse.triquetrum.core.feature/epl-v10.html
org.eclipse.triquetrum.core.feature/notice.html

How to add files to the top level with tycho is documented at
https://wiki.eclipse.org/Tycho/Demo_Projects/RCP_Application and
http://help.eclipse.org/neon/index.jsp?topic=/org.eclipse.pde.doc.user/tasks/pde_rootfiles.htm
In this case, the key was to edit
org.eclipse.triquetrum.core.feature/build.properties
and add
root = file:epl-v10.html,file:notice.html

Added epl-v10.html and notice.html to the toplevel. Bug #133

---

pom.xml

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=492412#c84

Comment out javadoc module. Bug #148

---

org.eclipse.triquetrum.python.service/src/main/java/org/eclipse/triquetrum/python/service/PythonService.java

Stop trying to reuse the input channel of Eclipse. When Eclipse is
run with -console (OSGi console) then Eclipse is already reading
from stdin. That means that Python is not able to and on Windows
it does not start properly.
Signed-off-by: Jonah Graham <jonah@kichwacoders.com>

Bug #141: Provide python its own input channel

---

org.eclipse.triquetrum.repository/publish.xml

Added copyZips rule for Bug#148 Releases on Eclipse Downloads

---

examples/org.eclipse.triquetrum.workflow.actor.plot.feature/feature.xml
org.eclipse.triquetrum.core.feature/feature.xml
org.eclipse.triquetrum.ptolemy.feature/feature.xml
org.eclipse.triquetrum.python.feature/feature.xml
org.eclipse.triquetrum.rcp.feature/feature.xml
org.eclipse.triquetrum.thirdparty.feature/feature.xml
org.eclipse.triquetrum.update/category.xml
org.eclipse.triquetrum.workflow.core.feature/feature.xml
org.eclipse.triquetrum.workflow.rcp.feature/feature.xml

Bug #145 Create a p2 repository
The incubation guide requires:
'6. Similarly, the names for update manager features must include the
word "incubation". For example, Eclipse Platform (Incubation)"'

Added '(Incubation)' to the category and feature names

---

org.eclipse.triquetrum.repository/Triquetrum.product

https://github.com/eclipse/triquetrum/issues/224

Mac OS: Added -data /tmp to prevent translocation message.

---

org.eclipse.triquetrum.repository/pom.xml

See https://github.com/eclipse/triquetrum/issues/187
RC1 Linux 64 zip file should create a directory

Added configuration so that Linux dist is in a subdirectory.

---

org.eclipse.triquetrum.repository/Triquetrum.product

Linux download fails to find modules
https://github.com/eclipse/triquetrum/issues/227
Erwin replied:
> I think this is due to the fact that you launch your RCP on a JDK 7
(cfr the 3rd line in the startup log). 
> Since Neon, Eclipse requires a JDK 8 to run on itself (although you
can develop in it for Java 7 applications or older).

Set osgi.requiredJavaVersion to 1.8: Bug #227

---

org.eclipse.triquetrum.repository/pom.xml

Signing the Windows .exe files failed because 
org.eclipse.triquetrum.workflow.editor.rcp.incubation-${release_name}.qualifier/win32/win32/x86/eclipsec.exe'
does not exist

Hard wired in the version number.  Bug #186

---

org.eclipse.triquetrum.repository/pom.xml

RC1 Mac Installer is from an unknown developer
https://github.com/eclipse/triquetrum/issues/186

Updated paths of Windows and Mac Binaries

---

org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/util/EditorUtils.java

Ports created in EMF Form were not guaranteed to have their Ptolemy
wrappedObject available when drawing connections on them.

#219: fix wrapping of Ptolemy Port for e.g. RecordDisassembler

---

org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd

adapt to change in GMF structure (tooling runtime seems to be gone)
and update oxygen content versions

#198: update target platform definition

---

releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd

See Bug 491951 - Unable to satisfy dependency from org.eclipse.swt
v20160317 to org.eclipse.swt.gtk.linux.aarch64
See
Bug #101 Fixed multi-platform build after last change for Bug #66
Bug #259 Update build to not use
http://eclipseguru.github.io/missing-swt-fragments/ 

Bug #259: Remove dependency on missing swt-fragments

---

plugins/core/org.eclipse.triquetrum.workflow.aoc.repository/META-INF/MANIFEST.MF

Bug #266: org.eclipse.triquetrum.workflow.aoc.repository is 
not signed 
The issue here was that there was no value for vendor in
MANIFEST.MF.

Bug #266: Added vendor to o.e.t.w.aoc.repository

---

plugins/core/org.eclipse.triquetrum.workflow.aoc.repository/META-INF/MANIFEST.MF

Initially, the org.eclipse.triquetrum.workflow.aoc.repository
bundle had iSencia as the vendor.  I changed it to
iSencia Belgium NV or something similar.  Erwin correctly
pointed out that as this bundle is in the triquetrum repo,
it should have Eclipse Triquetrum as the vendor.
Some of the bundles in the osgi-2-0 correctly have iScencia 
Belgium NV as the vendor.

Bug #215 Updated aoc vendor to Eclipse Triquetrum.

---

releng/org.eclipse.triquetrum.repository/publish.xml

Bug #281 Release Triquetrum 0.2.0
https://github.com/eclipse/triquetrum/issues/281

Bug #281	. Copy .tar.gz files to the download directory

---

examples/pom.xml
features/pom.xml
plugins/core/pom.xml
plugins/editor/pom.xml
plugins/extras/pom.xml
plugins/pom.xml
pom.xml

Missed some pom.xml files in the previous commit.
https://github.com/eclipse/triquetrum/issues/281

Bug #281: Update Versions: Adding more pom.xml files

---

releng/org.eclipse.triquetrum.repository/pom.xml

https://github.com/eclipse/triquetrum/issues/281

Bug #281 Release Triquetrum 0.2.0.  Updated to version 0.2.0

---

releng/org.eclipse.triquetrum.repository/pom.xml

Triquetrum Bug #315 Create 0.3.0M1 release

Eclipse no longer supports 32-bit images, so don't try to sign them.

---

setups/org.eclipse.triquetrum.developer.setup/TriquetrumDevelopment.setup

Triquetrum bug #323 Update the Triquetrum Oomph installer
Updated to https://download.eclipse.org/ecp/releases/releases_122/1220
Updated to 2019-09
Updated how we get the github password.

Finished updating setup to 2019-09.

---

pom.xml

Triquetrum Bug #344: Maven produces duplicate fetching messages.

Update Tycho to 1.6.0.

---

entitlement/triquetrum.entitlement
pom.xml
releng/org.eclipse.triquetrum.repository/pom.xml

Bug #358 macOS: The JVM shared library ... does not contain the
JNI_CreateJavaVM symbol
See
https://wiki.eecs.berkeley.edu/ptexternal/Main/EclipseAndSigningMacApps

Updated macOS signing to include Entitlements
