- CONTRIBUTING.md
This pull request adds CONTRIBUTING.md.
I'm learning how this all works, so hopefully this is not a huge mistake.
> Cxbrooks contributing

- CONTRIBUTING.md
Bug #8 Add CONTRIBUTING.md
Documented using more detailed branch names and other changes.
> Updated process after feedback from Erwin and Jay.

- CONTRIBUTING.md
Bug #10 Add pom.xml file so that we can build from the command line.
> Use simpler branch names.  Description of how to add Signed-off-by.

- pom.xml
Bug #29:  Add support for FindBugs to pom.xml
To invoke, run 'mvn findbugs:findbugs' or 'mvn site'
> Added FindBugs plugin

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ActorConfigureFeature.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/views/NamedObjDialog.java
#35 : Using an OperationCanceledException.
This is not ideal as it generates error stack traces each time in the equinox consoleLog, but seems to be the advised approach.
> #35 : Implement a first trial for cancel button

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/TriqDiagramEditor.java
> #54: editor must have a model name available in first setFocus()

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/TriqDiagramEditor.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/wizard/WizardUtils.java
also renames the Diagram EObject to reflect the new file name
> #75: implement save as

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/TriqDiagramBehavior.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/shapes/ptolemy/AbstractDrawingStrategy.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/shapes/ptolemy/DrawingStrategy.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/shapes/ptolemy/LineDrawingStrategy.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/shapes/ptolemy/PtolemyModelElementShape.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/shapes/ptolemy/RectangleDrawingStrategy.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/shapes/ptolemy/TextDrawingStrategy.java
> #73: introduce jface resourcemanager usage to resolve SWT leaks

- org.eclipse.triquetrum.repository/Triquetrum.product
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
> Update to Neon. Bug #66 (Mac OS X Edit Menu) still not fixed

- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.python.rpc.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.python.rpc.platform.tpd
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd
See https://wiki.eclipse.org/Triquetrum/Target_Platform_Definition
> Updated Python .tpd file to remove ref to Mars.  Bug #104

- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd
> Use http instead of https to refer to a p2 site: Bug #492412

- pom.xml
> Undo change that attempted to print env.

- org.eclipse.triquetrum.workflow.model.editor/plugin.properties
> Used sed to get rid of embedded \r chars.  Bug #122: Line Endings

- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/feature.xml
- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/license.html
- org.eclipse.triquetrum.core.feature/build.properties
- org.eclipse.triquetrum.core.feature/feature.xml
- org.eclipse.triquetrum.core.feature/license.html
- org.eclipse.triquetrum.ptolemy.feature/build.properties
- org.eclipse.triquetrum.ptolemy.feature/feature.xml
- org.eclipse.triquetrum.ptolemy.feature/license.html
- org.eclipse.triquetrum.python.feature/build.properties
- org.eclipse.triquetrum.python.feature/feature.xml
- org.eclipse.triquetrum.python.feature/license.html
- org.eclipse.triquetrum.rcp.feature/build.properties
- org.eclipse.triquetrum.rcp.feature/feature.xml
- org.eclipse.triquetrum.rcp.feature/license.html
- org.eclipse.triquetrum.thirdparty.feature/build.properties
- org.eclipse.triquetrum.thirdparty.feature/feature.xml
- org.eclipse.triquetrum.thirdparty.feature/license.html
- org.eclipse.triquetrum.workflow.core.feature/build.properties
- org.eclipse.triquetrum.workflow.core.feature/feature.xml
- org.eclipse.triquetrum.workflow.core.feature/license.html
- org.eclipse.triquetrum.workflow.model.edit/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.model/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.rcp.feature/build.properties
- org.eclipse.triquetrum.workflow.rcp.feature/feature.xml
- org.eclipse.triquetrum.workflow.rcp.feature/license.html
See https://www.eclipse.org/legal/guidetolegaldoc.php
> Completed checklist for legal docs for features.  Bug #134

- org.eclipse.triquetrum.core.feature/build.properties
- org.eclipse.triquetrum.core.feature/feature.xml
- org.eclipse.triquetrum.ptolemy.feature/build.properties
- org.eclipse.triquetrum.ptolemy.feature/feature.xml
- org.eclipse.triquetrum.python.feature/build.properties
- org.eclipse.triquetrum.python.feature/feature.xml
- org.eclipse.triquetrum.rcp.feature/build.properties
- org.eclipse.triquetrum.rcp.feature/feature.xml
- org.eclipse.triquetrum.thirdparty.feature/build.properties
- org.eclipse.triquetrum.thirdparty.feature/feature.xml
- org.eclipse.triquetrum.workflow.core.feature/build.properties
- org.eclipse.triquetrum.workflow.core.feature/feature.xml
- org.eclipse.triquetrum.workflow.rcp.feature/build.properties
- org.eclipse.triquetrum.workflow.rcp.feature/feature.xml
> Fixes for mvn verify.  Bug #134

- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/build.properties
- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/epl-v10.html
- org.eclipse.triquetrum.core.feature/build.properties
- org.eclipse.triquetrum.ptolemy.feature/build.properties
- org.eclipse.triquetrum.ptolemy.feature/epl-v10.html
- org.eclipse.triquetrum.python.feature/build.properties
- org.eclipse.triquetrum.python.feature/epl-v10.html
- org.eclipse.triquetrum.rcp.feature/build.properties
- org.eclipse.triquetrum.rcp.feature/epl-v10.html
- org.eclipse.triquetrum.thirdparty.feature/build.properties
- org.eclipse.triquetrum.thirdparty.feature/epl-v10.html
- org.eclipse.triquetrum.workflow.core.feature/build.properties
- org.eclipse.triquetrum.workflow.core.feature/epl-v10.html
- org.eclipse.triquetrum.workflow.rcp.feature/build.properties
- org.eclipse.triquetrum.workflow.rcp.feature/epl-v10.html
> Added epl-v10.html. Bug #134

- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/build.properties
- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/feature.properties
- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/feature.xml
also use a feature.properties file
> #134: get the plot example feature in line with the others

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/TriqFeatureProvider.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ModelElementConfigureFeature.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/PortUpdateFeature.java
- org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/impl/PortImpl.java
in actor configuration dialog.
> #95: support port single/multi configuration

- org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/util/PtObjectBuilderAndApplierVisitor.java
- org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/util/PtObjectBuilderVisitor.java
> #87: fix regression due to introduction of visitors

- org.eclipse.triquetrum.repository/publish.xml
See
https://wiki.eclipse.org/index.php?title=Milestone_and_Release_Builds
Signed-off-by: cxh <cxh@eecs.eecs.berkeley.edu>
> Added publish.xml so that we can create nightlies, Bug #148

- org.eclipse.triquetrum.repository/publish.xml
> Update project name.  Bug #148

- pom.xml
> Added eclipse-sign profile.  Bug #128

- org.eclipse.triquetrum.repository/Triquetrum.product
Bug #148: Make releases available on the Eclipse download server 
> Added M1 to the version number so that we can upload.

- org.eclipse.triquetrum.update/.project
- org.eclipse.triquetrum.update/category.xml
- org.eclipse.triquetrum.update/pom.xml
- pom.xml
Bug #145 Create a p2 update site
> Adding update site for Triquetrum

- org.eclipse.triquetrum.repository/Triquetrum.product
Bug #145 Add an update site
Still need to fix up version names for incubation.
> Added Triquetrum update site

- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/feature.xml
- org.eclipse.triquetrum.core.feature/feature.xml
- org.eclipse.triquetrum.ptolemy.feature/feature.xml
- org.eclipse.triquetrum.python.feature/feature.xml
- org.eclipse.triquetrum.rcp.feature/feature.xml
- org.eclipse.triquetrum.thirdparty.feature/feature.xml
- org.eclipse.triquetrum.workflow.core.feature/feature.xml
- org.eclipse.triquetrum.workflow.rcp.feature/feature.xml
Bug #145 p2 repository
Bug #120 Incubation
> Another attempt at removing '(Incubation)' from feature.xml

- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/feature.xml
- examples/org.eclipse.triquetrum.workflow.actor.plot/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.processing.model.impl/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.processing.service.impl/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.processing.service.impl/META-INF/p2.inf
- org.eclipse.triquetrum.python.service/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.python.service/META-INF/p2.inf
- org.eclipse.triquetrum.workflow.actor.ui/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.actor.ui/META-INF/p2.inf
- org.eclipse.triquetrum.workflow.core.feature/feature.xml
- org.eclipse.triquetrum.workflow.editor/META-INF/p2.inf
- org.eclipse.triquetrum.workflow.execution.impl/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.execution.impl/META-INF/p2.inf
- org.eclipse.triquetrum.workflow.rcp.feature/feature.xml
- org.eclipse.triquetrum.workflow.repository.impl.filesystem/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.repository.impl.filesystem/META-INF/p2.inf
- org.eclipse.triquetrum.workflow.ui/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.ui/META-INF/p2.inf
to be extra certain that bundles get started after being installed from
an update site
> #145: add feature deps, lazy start in manifests + p2.inf files

- org.eclipse.triquetrum.workflow.editor.palette/plugin.xml
- org.eclipse.triquetrum.workflow.editor/schema/org.eclipse.triquetrum.workflow.editor.paletteContribution.exsd
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/palette/PaletteTreeNode.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/palette/TriqPaletteBehavior.java
> #181: reuse existing palette group + add group ordering

- org.eclipse.triquetrum.workflow.editor/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.editor/schema/org.eclipse.triquetrum.workflow.editor.paletteContribution.exsd
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/TriqFeatureProvider.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/palette/TriqPaletteBehavior.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/palette/spi/PaletteConfigurationElement.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/palette/spi/PaletteEntryProvider.java
> #189: define palette SPI and first trial implementation

- examples/org.eclipse.triquetrum.workflow.actor.plot.feature/feature.xml
- org.eclipse.triquetrum.repository/Triquetrum.product
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.python.rpc.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.python.rpc.platform.tpd
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd
- org.eclipse.triquetrum.workflow.core.feature/feature.xml
- org.eclipse.triquetrum.workflow.rcp.feature/feature.xml
Bug #198 Update Triquetrum to use Oxygen
> Bug #198: Updated from Neon to Oxygen. Updated from 0.1.0 to 0.2.0M5

- examples/pom.xml
- javadoc/pom.xml
- pom.xml
Bug #198: Updated from Neon to Oxygen
> Further 0.1.0 to 0.2.0 changes.  Bug #198

- org.eclipse.triquetrum.repository/Triquetrum.product
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd
> #198: update versions/p2-repo for ECP and Orbit

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ActorAddFeature.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ActorUpdateFeature.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ModelElementLayoutFeature.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/shapes/ActorShapes.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/shapes/PortShapes.java
- org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/Direction.java
matching changes in direction on the actor sides.
> #158: finalize implementation of port relocation and rotation

- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.python.rpc.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.python.rpc.platform.tpd
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd
> #198: update targets to Oxygen M6 and latest orbit build

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ModelElementPasteFeature.java
- org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/util/PtolemyUtil.java
> #87: also copy referred variables along with selected model elements

- org.eclipse.triquetrum.workflow.editor/plugin.xml
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/preferences/ui/TriqPreferencePage.java
- org.eclipse.triquetrum.workflow.rcp.feature/feature.xml
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/.classpath
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/.gitignore
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/.project
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/META-INF/p2.inf
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/about.html
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/build.properties
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/plugin.xml
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/src/main/java/org/eclipse/triquetrum/workflow/repository/impl/filesystem/preferences/ui/WorkflowRepositoryPreferenceInitializer.java
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/src/main/java/org/eclipse/triquetrum/workflow/repository/impl/filesystem/preferences/ui/WorkflowRepositoryPreferencePage.java
- org.eclipse.triquetrum.workflow.repository.impl.filesystem.ui/src/main/java/org/eclipse/triquetrum/workflow/repository/impl/filesystem/preferences/ui/WorkflowRepositoryUIPlugin.java
- org.eclipse.triquetrum.workflow.repository.impl.filesystem/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.repository.impl.filesystem/src/main/java/org/eclipse/triquetrum/workflow/repository/impl/filesystem/WorkflowRepositoryPreferencesSupplier.java
- org.eclipse.triquetrum.workflow.repository.impl.filesystem/src/main/java/org/eclipse/triquetrum/workflow/repository/impl/filesystem/WorkflowRepositoryServiceImpl.java
- org.eclipse.triquetrum.workflow.repository.impl.filesystem/src/main/java/org/eclipse/triquetrum/workflow/repository/impl/filesystem/activator/Activator.java
- pom.xml
and handle preferences in the service implementation
> #183: add preferences page for file-based workflow repository service

- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
Graphiti release changed in the Oxygen repository.
> Fixing Hudson build before update to M7

- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.python.rpc.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.python.rpc.platform.tpd
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
- org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd
https://github.com/eclipse/triquetrum/issues/198
> Updated to more recent repositories.

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ParameterUpdateFeature.java
- org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/impl/NamedObjImpl.java
> #221: fix parameter renaming

- org.eclipse.triquetrum.repository/Triquetrum.product
- org.eclipse.triquetrum.workflow.model.edit/META-INF/MANIFEST.MF
- org.eclipse.triquetrum.workflow.model.edit/intro/intro.xml
- org.eclipse.triquetrum.workflow.model.edit/plugin.xml
See: https://wiki.eclipse.org/Triquetrum/Releng/Welcome_Pages
Bug #169 Create Welcome Support
https://github.com/eclipse/triquetrum/issues/169
> Test of modification of Welcome panel.

- setups/org.eclipse.triquetrum.developer.setup/TriquetrumDevelopment.setup
> #234: update oomph setup file to oxygen RC2

- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/TriqDiagramEditor.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/TriqToolBehaviorProvider.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/outline/DiagramEditorOutlinePage.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/outline/tree/TriqOutlineTreeViewer.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/util/EditorUtils.java
- org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/views/TriqSelectionSynchronizer.java
> #160 : guideline 6.21 outline/editor selection linking

- plugins/editor/org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/impl/PortImpl.java
i.o. previously always going from output to input
> #223: support drawing relations from input to output as well

- releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
- releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd
> Bug #215: Use osgi-2-0-2 p2 repo.

- releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
> Bug #215 Update Ptolemy Plugins: Update to recent osgi-2-0.

- releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
Bug #215 Update Ptolemy Plugins 
> Bug #215 Changed vendor to Ptolemy Project, Berkeley, California

- plugins/core/org.eclipse.triquetrum.workflow.aoc.repository/META-INF/MANIFEST.MF
- releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
- releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.tpd
> Bug #215: Update Ptolemy Plugins: Use Oxygen. Bumped Ptolemy Feature to 11.1

- releng/org.eclipse.triquetrum.target.platform/org.eclipse.triquetrum.target.platform.target
> Bug #215: Updated target after updating Ptolemy P2 site.

- releng/org.eclipse.triquetrum.repository/Triquetrum.product
> Bug #169: Welcome Window.  Set INTRO_START_PAGE

- plugins/editor/org.eclipse.triquetrum.workflow.rcp.common/META-INF/MANIFEST.MF
- plugins/editor/pom.xml
> #78: fix the  build for the new rcp.common bundle

- plugins/editor/org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/BoCategory.java
- plugins/editor/org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ActorAddFeature.java
- plugins/editor/org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/CompositeActorAddFeature.java
- plugins/editor/org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/FeatureConstants.java
- plugins/editor/org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/features/ModelElementPasteFeature.java
- plugins/editor/org.eclipse.triquetrum.workflow.editor/src/main/java/org/eclipse/triquetrum/workflow/editor/util/BuildDiagramElementsFromPtolemyElementCommand.java
> #289: pass icon info along in graphical model and to paste logic

- examples/pom.xml
- features/org.eclipse.triquetrum.ptolemy.feature/feature.xml
- features/org.eclipse.triquetrum.rcp.feature/feature.xml
- features/org.eclipse.triquetrum.workflow.core.feature/feature.xml
- features/org.eclipse.triquetrum.workflow.rcp.feature/feature.xml
- features/pom.xml
- plugins/core/pom.xml
- plugins/editor/org.eclipse.triquetrum.workflow.editor/META-INF/MANIFEST.MF
- plugins/editor/org.eclipse.triquetrum.workflow.model.viewmodel/META-INF/MANIFEST.MF
- plugins/editor/pom.xml
- plugins/extras/pom.xml
- plugins/pom.xml
- pom.xml
- releng/org.eclipse.triquetrum.repository/Triquetrum.product
- releng/org.eclipse.triquetrum.repository/pom.xml
- releng/org.eclipse.triquetrum.target.platform/pom.xml
- releng/org.eclipse.triquetrum.update/category.xml
- releng/org.eclipse.triquetrum.update/pom.xml
- tests/pom.xml
> #301: update version nrs to 0.2.1 release

- releng/org.eclipse.triquetrum.repository/Triquetrum.product
- releng/org.eclipse.triquetrum.repository/pom.xml
- releng/org.eclipse.triquetrum.repository/site.xml
Triquetrum Bug #315 Create 0.3.0M1 release
> Updates for 0.3.0M1

- releng/org.eclipse.triquetrum.repository/pom.xml
Triquetrum Bug #319 Updates for 0.3.0M1
> Sign the 0.3.0M1 files.

- pom.xml
- releng/org.eclipse.triquetrum.repository/Triquetrum.product
Triquetrum Bug #322 Create a 0.3.0M2 release
See https://wiki.eclipse.org/Triquetrum/Releng/Milestone_Builds#Create_a_Triquetrum_Milestone_Build
> Updated to 0.3.0M2.

- releng/org.eclipse.triquetrum.repository/Triquetrum.product
- releng/org.eclipse.triquetrum.repository/pom.xml
Triquetrum Bug #331 Create a Triquetrum 0.3.0M3 Milestone.
> Updated version to Triquetrum 0.3.0M3

- releng/org.eclipse.triquetrum.repository/Triquetrum.product
- releng/org.eclipse.triquetrum.repository/pom.xml
Triquetrum Bug #334 Update version numbers to 0.3.0
> Updated version number to 0.3.0

- releng/org.eclipse.triquetrum.repository/Triquetrum.product
- releng/org.eclipse.triquetrum.repository/pom.xml
Triquetrum Bug #336 Update version to 0.3.1
> Updated to 0.3.1.

- examples/pom.xml
- features/pom.xml
- plugins/core/pom.xml
- plugins/editor/pom.xml
- plugins/extras/pom.xml
- plugins/pom.xml
- pom.xml
- releng/org.eclipse.triquetrum.repository/Triquetrum.product
- releng/org.eclipse.triquetrum.repository/pom.xml
- releng/org.eclipse.triquetrum.repository/site.xml
- releng/org.eclipse.triquetrum.target.platform/pom.xml
- releng/org.eclipse.triquetrum.update/pom.xml
Bug #347 Update to 0.4.0
See https://wiki.eclipse.org/Triquetrum/Releng/Milestone_Builds
> Updated version to 0.4.0

- CONTRIBUTING.md
Bug 566534 [release] science.triquetrum 0.4.0
> Updated to ECA

- examples/pom.xml
- features/pom.xml
- plugins/core/pom.xml
- plugins/editor/pom.xml
- plugins/extras/pom.xml
- plugins/pom.xml
- pom.xml
- releng/org.eclipse.triquetrum.repository/Triquetrum.product
- releng/org.eclipse.triquetrum.repository/pom.xml
- releng/org.eclipse.triquetrum.repository/site.xml
- releng/org.eclipse.triquetrum.target.platform/pom.xml
- releng/org.eclipse.triquetrum.update/pom.xml
Bug #376 Update to 0.4.1
See http://wiki.eclipse.org/Triquetrum/Releng/Milestone_Builds
> Updated to 0.4.1
